Here we will learn how to work with numpy arrays

In [2]:
import numpy as np

# Create Arrays with List

In [3]:
mylist = [1,2,3]
arr = np.array(mylist)
arr

array([1, 2, 3])

To create a 2d array we have to pass a list of list

In [4]:
my_matrix = [[1,2,3], [4,5,6], [7,8,9]]
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# numpy's built-in methods to generate arrays

np.arange(start, stop, step)

In [5]:
 np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
# it will exclude the stop, to get 10 we need to pass (0,11)
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [7]:
# with step
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [8]:
np.arange(0,100)
# it looks like 2d array but it is actually 1d array, bc there is only one bracket in opening and closing.

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

# Specific type of Arrays

Arrays of all Zeros

In [9]:
# To generate vector
np.zeros(3)

array([0., 0., 0.])

In [10]:
np.zeros(100)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [11]:
# To generate matrix we have to pass a tupple (raws,columns)
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [12]:
np.zeros((7,9))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

Arrays of Ones


In [13]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [14]:
np.ones(50)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [15]:
# 2D
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [16]:
np.ones((7,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

# np.linspace(start, stop, numbers)

In [17]:
np.linspace(0,5)


array([0.        , 0.10204082, 0.20408163, 0.30612245, 0.40816327,
       0.51020408, 0.6122449 , 0.71428571, 0.81632653, 0.91836735,
       1.02040816, 1.12244898, 1.2244898 , 1.32653061, 1.42857143,
       1.53061224, 1.63265306, 1.73469388, 1.83673469, 1.93877551,
       2.04081633, 2.14285714, 2.24489796, 2.34693878, 2.44897959,
       2.55102041, 2.65306122, 2.75510204, 2.85714286, 2.95918367,
       3.06122449, 3.16326531, 3.26530612, 3.36734694, 3.46938776,
       3.57142857, 3.67346939, 3.7755102 , 3.87755102, 3.97959184,
       4.08163265, 4.18367347, 4.28571429, 4.3877551 , 4.48979592,
       4.59183673, 4.69387755, 4.79591837, 4.89795918, 5.        ])

In [18]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

# Identity Matrix eye()

In [ ]:
#np.eye(N,M,k)
# N = Number of rows in the output
# M = Number of columns in the output. If None, defaults to `N`
# k = Index of the diagonal: 0 (the default) refers to the main diagonal, a positive value refers to an upper diagonal, 
# and a negative value to a lower diagonal.

In [43]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [41]:
np.eye(5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [38]:
np.eye(7,5) 

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [42]:
np.eye(7,5,-2)   # k= -2 to change diagonal position of Ones. 

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# Array of Random Numbers

# np.random.rand()

In [ ]:
# It is used to generate arrays of random numbers from 0 to 1. 

In [45]:
np.random.rand() # If no argument is given a single Python float is returned.

0.6233826177320672

In [49]:
np.random.rand(20)  # only one argument for 1D array

array([0.61455268, 0.03052702, 0.07921867, 0.60600085, 0.80043927,
       0.78017609, 0.31183506, 0.18874842, 0.94992015, 0.40503401,
       0.98975458, 0.98987335, 0.8999151 , 0.66795361, 0.34350572,
       0.38566512, 0.44606786, 0.96613666, 0.80868026, 0.92381369])

In [55]:
np.random.rand(5,4)  # for 2D we don't pass tupple like np.zeros((5,4)) and np.ones((5,4)), we simply pass two arguments.

array([[0.83283124, 0.6801304 , 0.78438147, 0.59395493],
       [0.89052688, 0.43557386, 0.73526829, 0.07806767],
       [0.65229583, 0.946477  , 0.90227711, 0.50185851],
       [0.25370205, 0.66332722, 0.25752226, 0.39388137],
       [0.60190835, 0.61450687, 0.54294112, 0.8191896 ]])

In [56]:
np.random.rand(5)

array([0.6199011 , 0.41910313, 0.48034188, 0.09487542, 0.86316137])

In [59]:
np.random.rand(2,3)

array([[0.84833317, 0.59346395, 0.52092869],
       [0.12522474, 0.9527822 , 0.50312909]])

# np.random.randn()

In [ ]:
# Return a sample (or samples) from the "standard normal" distribution.

In [72]:
np.random.randn()  # ramdom float if no argument is given

0.9593531229349601

In [90]:
np.random.randn(20)

array([ 1.26149075, -0.09578716, -1.82294022, -1.33662714,  0.87651933,
        0.4410758 ,  0.11736883, -0.62132633, -0.41739279, -0.06552015,
       -2.07333524,  0.34695947,  1.83834692, -1.39559271,  2.14453712,
        1.48178293,  1.90503721,  0.08388494,  1.41702844,  1.40031032])

In [91]:
np.random.randn(5,4)

array([[ 1.24440032, -0.29872622, -2.37881726, -0.34903516],
       [ 1.86308746,  0.09122833, -0.68142474, -1.47556471],
       [-0.66256309,  1.21305174,  0.60509263, -0.11735133],
       [ 1.13616096, -0.93777892, -0.23629547,  0.05464473],
       [-1.52376853, -0.04370165,  0.82274419,  0.80383886]])

# np.random.randint()

In [ ]:
# Return random integers from `low` (inclusive) to `high` (exclusive) and given `size` (n, m, k) 

In [110]:
np.random.randint(5) # low = 5, it will give single random int from [0 to 5),because size is not given 

2

In [106]:
np.random.randint(5,8) # random int from [5 to 8). again size is missing

6

In [107]:
np.random.randint(5,8,6) # 1D array of size 6, from [5 to 8).

array([6, 5, 5, 5, 6, 7])

In [111]:
np.random.randint(5,8,(2,3)) # 2d array of 2x3, from int values [5 to 8).

array([[6, 6, 6],
       [5, 7, 5]])

In [112]:
np.random.randint(0,50, (7,4))

array([[25, 26,  7, 39],
       [30, 25, 11, 11],
       [29, 23, 30,  0],
       [33, 22, 24, 23],
       [28, 37, 29,  2],
       [18, 33, 38, 33],
       [44, 41,  6, 30]])