# myarray.reshape()

In [2]:
import numpy as np

In [10]:
# create an array using arange
myarr = np.arange(16)
myarr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [11]:
# Now we can chage the shape(keeping the size same) of this array using reshape
myarr.reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [13]:
myarr.reshape(2,8)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

To reshape any array, Row x Column = size, 16x1 = 4x4 = 8x2 = 16, or we will get an error.

# max(), min(), argmax(), argmin()

In [16]:
randarr = np.random.randint(0,20,(3,4))
randarr

array([[16, 17, 18, 18],
       [ 3, 12,  5, 16],
       [11,  5, 12,  5]])

In [17]:
randarr.max()  # max value in array

18

In [18]:
randarr.min()  # min value in array

3

In [19]:
randarr.argmax()  # index of max value

2

In [20]:
randarr.argmin()  # index of min value

4

# .shape and .dtype

In [21]:
# to find shape of an array
myarr.shape

(16,)

In [22]:
myarr = myarr.reshape(4,4)
myarr.shape

(4, 4)

In [23]:
randarr.shape

(3, 4)

To check datatype of array

In [24]:
myarr.dtype

dtype('int32')

In [25]:
randarr.dtype

dtype('int32')

In [27]:
r_arr = np.random.rand(10)
r_arr

array([0.39024444, 0.40199198, 0.09698492, 0.32435409, 0.15914485,
       0.61428423, 0.79799521, 0.40672921, 0.29999547, 0.01046393])

In [28]:
r_arr.dtype

dtype('float64')