In [1]:
import numpy as np

In [2]:
arr2d = np.array([[5,10,15], [20,25,30], [35,40,45]])
arr2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [4]:
# access 5
arr2d[0][0]      # Double bracket notation

5

In [5]:
# access 30
arr2d[1][2]

30

In [7]:
arr2d[2,1]      # Single bracket notation (reccommanded)

40

In [34]:
arr2d[0,0]

5

## slicing 2d arrays

In [35]:
arr = np.arange(25).reshape(5,5)

In [36]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [37]:
# slice upper right corner upto 3 values
# rmove 4th and 5th row, remove 0th and 1st column
# arr[0,1,2 and 2,3,4]  include before 3(excluding 3), and include after 2(including 2)
arr[:3, 2:]

array([[ 2,  3,  4],
       [ 7,  8,  9],
       [12, 13, 14]])

In [38]:
# lower left
arr[2:, :3]

array([[10, 11, 12],
       [15, 16, 17],
       [20, 21, 22]])

In [39]:
# upper left
arr[:3, :3]

array([[ 0,  1,  2],
       [ 5,  6,  7],
       [10, 11, 12]])

In [40]:
# lower right
arr[2:, 2:]

array([[12, 13, 14],
       [17, 18, 19],
       [22, 23, 24]])

In [43]:
# grab 3rd row only
arr[3]

array([15, 16, 17, 18, 19])

In [44]:
# grab 3rd column only
arr[:, 3]

array([ 3,  8, 13, 18, 23])

# Conditional Selection

In [45]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [64]:
# arr > 15 will create an array of boolean values, whic we will save in bool_arr
bool_arr = arr > 14
bool_arr

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [65]:
arr_greater_than_15 = arr[bool_arr] # now we will pass it in original array.

In [66]:
arr_greater_than_15

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [67]:
# This long process is same as
GT15 = arr[arr>14]

In [68]:
GT15

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [72]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### More exapmle

In [77]:
even_arr = arr[arr%2 == 0]
even_arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24])

In [78]:
odd_arr = arr[arr%2 != 0]
odd_arr

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23])